# Generated by Django 5.0.3 on 2025-03-24 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_userprofile_profile_picture'),
        ('core', '0006_alter_notification_link_and_more'),
    ]

    operations = [
    ]
